---
kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: bitsbeats/drone-helm3
    settings:
      kube_api_server:
        from_secret: api-server
      kube_token:
        from_secret: kube_token
      chart: ./helm-chart
      release: go-app
      namespace: default
      wait: true
      force: true
