steps:
  - name deploy
    image: bitsbeats/drone-helm3
    settings:
      kube_api_server: https://cebcfaef-35a6-44b9-a501-25cb26cf610e.k8s.ondigitalocean.com
      kube_token:
        from_secret: kube_token
      chart: .\go-k8s\helm-chart
      release: myapp-staging
      wait: true
      force: true
