# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

imagePullSecrets:
  - name: regcred

image:
  repository: slavchokirov/go-k8s
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  name: go-app
  type: NodePort
  externalPort: 3000
  internalPort: 3000

service:
  enabled: true
  type: LoadBalancer
  ports:
    app:
      port: 3000
      targetPort: 3000
      protocol: TCP

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
